application: apps
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# URLS and apps
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
#Static files
- url: /asciichan/stylesheets
  static_dir: asciichan/stylesheets

- url: /blog/stylesheets
  static_dir: blog/stylesheets

- url: /stylesheets
  static_dir: stylesheets

#Main
- url: /
  script: main.app

#Ascii work
- url: /ascii.*
  script: asciichan.asciichan.app

#Blog work
- url: /blog.*
  script: blog.blog.app

- url: /blog/(.*)
  script: blog.blog.app


# Libraries!
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
